[package]
name = "board-game-geom"
version = "0.1.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gifnksm/othello"
description = "Geometry library for board game."
